# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

Fluxo.create({
  curso: "Ciência da Computação",
  nodes: [
    {id:"C1",name:"Cálculo 1",group:1},
    {id:"APC",name:"Algoritmos e Programação de Computadores",group:1},
    {id:"ISC",name:"Introdução a Sistemas de Computação",group:1},
    {id:"C2",name:"Cálculo 2",group:2},
    {id:"CL",name:"Circuitos Lógicos",group:2},
    {id:"LCL",name:"Laboratório de Circuitos Lógicos",group:2},
    {id:"ED",name:"Estrutura de Dados",group:2},
    {id:"FTC",name:"Fundamentos Teóricos da Computação",group:2},
    {id:"IAL",name:"Introdução a Álgebra Linear",group:2},
    {id:"PE",name:"Probabilidade e Estatística",group:3},
    {id:"CN",name:"Cálculo Numérico",group:3},
    {id:"A1",name:"Álgebra 1",group:3},
    {id:"TP1",name:"Técnicas de Programação 1",group:3},
    {id:"OAC",name:"Organização e Arquitetura de Computadores",group:3},
    {id:"TP2",name:"Técnicas de Programação 2",group:4},
    {id:"LC1",name:"Lógica Computacional 1",group:4},
    {id:"RC",name:"Redes de Computadores",group:4},
    {id:"TAG",name:"Teoria e Aplicação de Grafos",group:4},
    {id:"BD",name:"Bancos de Dados",group:5},
    {id:"IIA",name:"Introdução a Inteligência Artificial",group:5},
    {id:"LP",name:"Linguagens de Programação",group:5},
    {id:"ES",name:"Engenharia de Software",group:5},
    {id:"PC",name:"Programação Concorrente",group:5},
    {id:"CE",name:"Computação Experimental",group:6},
    {id:"SI",name:"Sistemas de Informação",group:6},
    {id:"SB",name:"Software Básico",group:6},
    {id:"AC",name:"Autômatos e Computabilidade",group:6},
    {id:"FSO",name:"Fundamentos de Sistemas Operacionais",group:6},
    {id:"IS",name:"Informática e Sociedade",group:7},
    {id:"PAA",name:"Projeto e Análise de Algoritmos",group:7},
    {id:"SC",name:"Segurança Computacional",group:7},
    {id:"C",name:"Compiladores",group:7}
  ],
  links: [
    {source:"C1",target:"PE"},
    {source:"C1",target:"C2"},
    {source:"C1",target:"PAA"},
    {source:"APC",target:"ED"},
    {source:"APC",target:"CL"},
    {source:"APC",target:"LCL"},
    {source:"FTC",target:"LC1"},
    {source:"C2",target:"CN"},
    {source:"CL",target:"OAC"},
    {source:"LCL",target:"OAC"},
    {source:"ED",target:"PAA"},
    {source:"ED",target:"BD"},
    {source:"ED",target:"SB"},
    {source:"ED",target:"IIA"},
    {source:"ED",target:"LP"},
    {source:"ED",target:"TP1"},
    {source:"ED",target:"TAG"},
    {source:"ED",target:"RC"},
    {source:"ED",target:"LC1"},
    {source:"ED",target:"SI"},
    {source:"ED",target:"CE"},
    {source:"OAC",target:"SB"},
    {source:"OAC",target:"PC"},
    {source:"RC",target:"SC"},
    {source:"TP1",target:"TP2"},
    {source:"TP1",target:"ES"},
    {source:"LP",target:"ES"},
    {source:"LP",target:"C"},
    {source:"SB",target:"C"},
    {source:"TP2",target:"PC"},
    {source:"PC",target:"FSO"},
    {source:"A1",target:"AC"},
    {source:"AC",target:"C"}
  ]
})

Fluxo.create({
  curso: "Engenharia de Software",
  nodes: [
    {id:"C1",name:"Cálculo 1",group:1},
    {id:"APC",name:"Algoritmos e Programação de Computadores",group:1},
    {id:"DIAC",name:"Desenho Industrial Assistido por Computador",group:1},
    {id:"EA",name:"Engenharia e Ambiente",group:1},
    {id:"IE",name:"Introdução à Engenharia",group:1},
    {id:"C2",name:"Cálculo 2",group:2},
    {id:"F1",name:"Física 1",group:2},
    {id:"FE1",name:"Física Experimental 1",group:2},
    {id:"IAL",name:"Introdução à Àlgebra Linear",group:2},
    {id:"PEAE",name:"Probabilidade e Estatística Aplicada à Engenharia",group:2},
    {id:"DS",name:"Desenvolvimento de Software",group:2},
    {id:"MNE",name:"Métodos Numéricos para Engenharia",group:3},
    {id:"EE",name:"Engenharia Econômica",group:3},
    {id:"HC",name:"Humanidades e Cidadania",group:3},
    {id:"TED1",name:"Teoria de Eletrônica Digital 1",group:3},
    {id:"PED1",name:"Prática de Eletrônica Digital 1",group:3},
    {id:"OO",name:"Orientação a Objetos",group:3},
    {id:"MD1",name:"Matemática Discreta 1",group:3},
    {id:"GPQ",name:"Gestão da Produção e Qualidade",group:4},
    {id:"MDS",name:"Métodos de Desenvolvimento de Software",group:4},
    {id:"ED1",name:"Estrutura de Dados 1",group:4},
    {id:"FAC",name:"Fundamentos de Arquiteturas de Computadores",group:4},
    {id:"MD2",name:"Matemática Discreta 2",group:4},
    {id:"IHC",name:"Interação Humano Computador",group:5},
    {id:"RS",name:"Requisitos de Software",group:5},
    {id:"SBD1",name:"Sistemas de Banco de Dados 1",group:5},
    {id:"FSO",name:"Fundamentos de Sistemas Operacionais",group:5},
    {id:"CO1",name:"Compiladores 1",group:5},
    {id:"ED2",name:"Estruturas de Dados 2",group:5},
    {id:"QS1",name:"Qualidade de Software 1",group:6},
    {id:"TS",name:"Testes de Software",group:6},
    {id:"ADS",name:"Arquitetura e Desenho de Software",group:6},
    {id:"FRC",name:"Fundamentos de Redes de Computadores",group:6},
    {id:"SBD2",name:"Sistemas de Banco de Dados 2",group:6},
    {id:"PAA",name:"Projeto e Análise de Algoritmos",group:6},
    {id:"TPPE",name:"Técnicas de Programação em Plataformas Emergentes",group:7},
    {id:"PP",name:"Paradigmas de Progamação",group:7},
    {id:"FSE",name:"Fundamentos de Sistemas Embarcados",group:7},
    {id:"PSPD",name:"Programação para Sistemas Paralelos e Distribuídos",group:7},
    {id:"EPS",name:"Engenharia de Produto de Software",group:8},
    {id:"GCES",name:"Gerência de Configuração e Evolução de Software",group:8}
  ],
  links: [
    {source:"C1",target:"C2"},
    {source:"C1",target:"PEAE"},
    {source:"C1",target:"PAA"},
    {source:"APC",target:"OO"},
    {source:"APC",target:"DS"},
    {source:"APC",target:"ED1"},
    {source:"DIAC",target:"IHC"},
    {source:"C2",target:"MNE"},
    {source:"IAL",target:"TED1"},
    {source:"IAL",target:"PED1"},
    {source:"EE",target:"GPQ"},
    {source:"TED1",target:"FAC"},
    {source:"OO",target:"MDS"},
    {source:"OO",target:"PP"},
    {source:"MD1",target:"MD2"},
    {source:"GPQ",target:"QS1"},
    {source:"MDS",target:"IHC"},
    {source:"MDS",target:"RS"},
    {source:"MDS",target:"TS"},
    {source:"ED1",target:"CO1"},
    {source:"ED1",target:"ED2"},
    {source:"ED1",target:"PAA"},
    {source:"MD2",target:"SBD1"},
    {source:"IHC",target:"QS1"},
    {source:"RS",target:"ADS"},
    {source:"SBD1",target:"SBD2"},
    {source:"FSO",target:"FRC"},
    {source:"FSO",target:"FSE"},
    {source:"CO1",target:"PP"},
    {source:"ED2",target:"PSPD"},
    {source:"TS",target:"TPPE"},
    {source:"TS",target:"GCES"},
    {source:"ADS",target:"PP"},
    {source:"FRC",target:"PSPD"},
    {source:"TPPE",target:"EPS"}
  ]
})
